---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - catalogs/finalizers
  verbs:
  - update
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - catalogs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - microservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - microservices/finalizers
  verbs:
  - update
- apiGroups:
  - enbuild.vivsoft.io
  resources:
  - microservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - GitRepository
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
