apiVersion: enbuild.vivsoft.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: enbuild-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: enbuild-crd
  name: hhs
spec:
  owner: juned
