apiVersion: enbuild.vivsoft.io/v1alpha1
kind: Catalog
metadata:
  labels:
    app.kubernetes.io/name: catalog
  name: bigbang
spec:
  role: devops
  type: helm
  description: "Platform One BigBang"
  sourceRef:
    kind: GitRepository
    name: bigbang-catalog
    namespace: default
  readme_file_path: "README.md"
  image_path: images/bigbang.png
  components: 
    - name: repo
      tool_type: "Settings"
      variable_file_path: "bigbang/envs/dev/values/repo.yaml"
      image_path: "images/gear.png"
    - name: istio
      tool_type: "Service Mesh"
      variable_file_path: "bigbang/envs/dev/values/istio.yaml"
      image_path: "images/istio.png"
    - name: istiooperator
      tool_type: "Service Mesh"
      variable_file_path: "bigbang/envs/dev/values/istiooperator.yaml"
      image_path: "images/istio.png"
    - name: jaeger
      tool_type: "Service Mesh"
      variable_file_path: "bigbang/envs/dev/values/jaeger.yaml"
      image_path: "images/jaeger.png"