apiVersion: enbuild.vivsoft.io/v1alpha1
kind: Catalog
metadata:
  labels:
    app.kubernetes.io/name: catalog
  name: bigbang
spec:
  role: devops
  type: helm
  description: "Platform One BigBang"
  repository: "https://gitlab.com/enbuild-staging/iac-templates/bigbang"
  project_id: 39029682
  readme_file_path: "README.md"
  ref: main
  image_path: images/mlflow-logon.png
  components: 
    - name: mlflow
      readme_file_path: "README.md"
      variable_file_path: "kustomization.yaml"
      image_path: "images/mlflow-logon.png"
