apiVersion: enbuild.vivsoft.io/v1alpha1
kind: Application
metadata:
  name: hhs
spec:
  owner: vivsoftorg2
  infrastrcture: eks_for_hhs
  logs: logs_url
  traces: traces_url
  dashbord: dashboard_url
  microservices:
   - name: hhs-frontend
     template: 
        owner: vivsoftorg
        repository: sw_template_react
   - name: hhs-backend
     template: 
        owner: vivsoftorg
        repository: sw_template_nodejs
  secretRef:
    name: repository-credentials