apiVersion: enbuild.vivsoft.io/v1alpha1
kind: Application
metadata:
  name: hhs
spec:
  owner: juned
  infrastrcture: eks_for_hhs
  logs: logs_url
  traces: traces_url
  dashbord: dashboard_url
  microservices:
   - name: hhs-frontend
     template: webapp-react
   - name: hhs-backend
     template: nodejs
  secretRef:
    name: repository-credentials