---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bigbang-catalog
  namespace: default
spec:
  interval: 1m0s
  url: https://gitlab.com/enbuild-staging/iac-templates/bigbang
  ref:
    branch: main
  secretRef:
    name: repository-credentials