---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bigbang-catalog
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/VivSoftOrg2/juned_bb_10_feb_2023_gh.git
  ref:
    branch: main
  secretRef:
    name: repository-credentials